import { useState } from 'react';
import { FileText, Upload, Sparkles, CheckCircle2, AlertTriangle, ShieldCheck, ArrowRight, X, Plus } from 'lucide-react';
import { cn } from '@/lib/utils';

const input = 'w-full rounded-xl border border-border bg-card px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-sky/20 focus:border-sky';
const label = 'text-[11px] font-bold uppercase tracking-wider text-muted-foreground';

export default function NouveauxDossiers() {
  const [category, setCategory] = useState('Crédit');
  const [files, setFiles] = useState<File[]>([]);
  const [analyzed, setAnalyzed] = useState(false);
  const [validated, setValidated] = useState(false);
  const addFiles = (e: React.ChangeEvent<HTMLInputElement>) => setFiles(Array.from(e.target.files || []));
  const analyze = () => setAnalyzed(true);
  return <div className="space-y-7 max-w-[1400px]">
    <div className="flex flex-wrap items-start justify-between gap-4">
      <div><div className="flex items-center gap-2 text-sky text-xs font-bold mb-2"><Sparkles size={15}/> ASSISTANT DE CONSTITUTION</div><h1 className="text-3xl font-black text-navy font-syne">Nouveaux dossiers</h1><p className="text-muted-foreground mt-1">Créez, documentez et orientez un dossier avec contrôle humain à chaque étape.</p></div>
      <div className="flex gap-2"><span className="px-3 py-2 rounded-lg bg-amber-50 text-amber-700 text-xs font-bold">Brouillon · non validé</span><button onClick={()=>setValidated(true)} className="px-4 py-2 rounded-xl bg-navy text-white text-sm font-bold">{validated ? 'Dossier validé' : 'Enregistrer le brouillon'}</button></div>
    </div>
    <div className="grid grid-cols-1 lg:grid-cols-[1fr_370px] gap-6">
      <div className="space-y-6">
        <section className="bg-card border border-border rounded-2xl p-6"><h2 className="font-bold text-navy flex items-center gap-2 mb-5"><FileText size={18} className="text-sky"/> Informations essentielles</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Field l="Référence / numéro du dossier" p="Ex. ND-2026-00421"/><Field l="Date de création" type="date"/><Field l="Client / débiteur / contrepartie" p="Nom ou raison sociale"/><Field l="Agence / direction" p="Agence Tunis Centre"/>
            <div><label className={label}>Type de dossier</label><select className={input} value={category} onChange={e=>setCategory(e.target.value)}><option>Crédit</option><option>Opération bancaire</option><option>Garantie</option><option>Litige commercial</option><option>Autre</option></select></div><Field l="Sous-type / catégorie" p={category === 'Crédit' ? 'Financement PME' : 'Préciser la catégorie'}/><Field l="Montant concerné" p="0,00 TND"/><Field l="Responsable du dossier" p="Rechercher un collaborateur"/>
          </div>
          {category === 'Garantie' && <div className="mt-4 p-4 rounded-xl bg-sky/5 border border-sky/20"><p className="text-xs font-bold text-sky mb-2">Champs spécifiques garanties</p><div className="grid md:grid-cols-2 gap-4"><Field l="Type de garantie" p="Caution, hypothèque…"/><Field l="Valeur estimée" p="0,00 TND"/></div></div>}
        </section>
        <section className="bg-card border border-border rounded-2xl p-6"><h2 className="font-bold text-navy mb-5">Situation et qualification</h2><div className="grid md:grid-cols-3 gap-4"><Field l="Statut" p="À qualifier"/><Field l="Priorité" p="Normale"/><Field l="Échéance importante" type="date"/></div><div className="grid md:grid-cols-2 gap-4 mt-4"><Field l="Nature de la créance / opération" p="Décrire l'objet du dossier"/><Field l="Garanties disponibles" p="Lister les garanties"/></div><label className={label+' block mt-4'}>Observations / informations juridiques et financières</label><textarea className={input+' mt-2 min-h-24'} placeholder="Ajoutez les éléments connus, obligations, clauses ou points d'attention…"/></section>
        <section className="bg-card border border-border rounded-2xl p-6"><div className="flex justify-between items-center mb-4"><div><h2 className="font-bold text-navy flex items-center gap-2"><Upload size={18} className="text-sky"/> Documents justificatifs</h2><p className="text-xs text-muted-foreground mt-1">Les originaux restent inchangés et séparés des données IA.</p></div><label className="cursor-pointer px-3 py-2 bg-sky text-white rounded-lg text-xs font-bold"><Plus size={14} className="inline mr-1"/>Importer<input type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx" className="hidden" onChange={addFiles}/></label></div><div className="border-2 border-dashed border-border rounded-xl p-6 text-center"><Upload className="mx-auto text-muted-foreground mb-2"/><p className="text-sm font-semibold">PDF, Word ou Excel · plusieurs fichiers</p><p className="text-xs text-muted-foreground">Déposez vos contrats, actes et correspondances ici</p></div>{files.length>0&&<div className="mt-3 space-y-2">{files.map(f=><div key={f.name} className="flex items-center justify-between p-3 bg-mist rounded-lg text-sm"><span className="flex gap-2 items-center"><FileText size={16} className="text-sky"/>{f.name}</span><button onClick={()=>setFiles(files.filter(x=>x!==f))}><X size={15}/></button></div>)}</div>}</section>
      </div>
      <aside className="space-y-5"><div className="bg-navy text-white rounded-2xl p-6"><div className="flex items-center gap-2 text-sky text-xs font-bold"><Sparkles size={17}/> ANALYSE INTELLIGENTE IA</div><h2 className="text-xl font-bold mt-3">Constituer le dossier</h2><p className="text-white/60 text-sm mt-2">L'IA extrait les données, signale les manques et propose les prochaines actions. Chaque donnée doit être vérifiée.</p><button onClick={analyze} className="mt-5 w-full flex justify-center items-center gap-2 py-3 rounded-xl bg-sky hover:bg-sky/90 font-bold text-sm"><Sparkles size={16}/> Analyser maintenant</button></div>
      {analyzed ? <div className="bg-card border border-border rounded-2xl p-5 space-y-4"><div className="flex justify-between"><h3 className="font-bold text-navy">Pré-analyse du dossier</h3><span className="text-xs text-emerald-600 font-bold">Terminée</span></div><Insight icon={CheckCircle2} color="text-emerald-600" title="Informations extraites" text={`${files.length || 0} document(s) analysé(s) · 6 éléments identifiés`}/><Insight icon={AlertTriangle} color="text-amber-600" title="2 informations manquantes" text="Échéance contractuelle · justificatif de garantie"/><Insight icon={ShieldCheck} color="text-sky" title="Vérification humaine requise" text="Montant et parties concernées à confirmer"/><div className="pt-3 border-t border-border text-xs text-muted-foreground">Source : document.pdf · page 2 · Données extraites par IA</div><button className="w-full text-sm font-bold text-sky flex justify-center items-center gap-2">Voir la synthèse structurée <ArrowRight size={15}/></button></div> : <div className="bg-card border border-border rounded-2xl p-5"><h3 className="font-bold text-navy mb-3">Parcours recommandé</h3>{['Créer le dossier','Importer les pièces','Analyser par IA','Vérifier et valider'].map((x,i)=><div className="flex gap-3 items-center py-2 text-sm" key={x}><span className="w-6 h-6 rounded-full bg-mist text-xs flex items-center justify-center font-bold">{i+1}</span>{x}</div>)}</div>}</aside>
    </div>
  </div>;
}
function Field({l,p,type='text'}:{l:string;p?:string;type?:string}){return <div><label className={label}>{l}</label><input type={type} placeholder={p} className={input+' mt-2'}/></div>}
function Insight({icon:Icon,color,title,text}:{icon:any;color:string;title:string;text:string}){return <div className="flex gap-3"><Icon size={18} className={color}/><div><p className="text-sm font-bold text-navy">{title}</p><p className="text-xs text-muted-foreground mt-1">{text}</p></div></div>}
