// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

let SUPABASE_URL = "https://placeholder-co-db.supabase.co";
if (typeof rawUrl === "string" && (rawUrl.startsWith("http://") || rawUrl.startsWith("https://"))) {
  SUPABASE_URL = rawUrl;
}

let SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy_key";
if (typeof rawKey === "string" && rawKey.trim() !== "" && !rawKey.includes("YOUR_SUPABASE")) {
  SUPABASE_PUBLISHABLE_KEY = rawKey;
}

const safeFetch = async (url: RequestInfo | URL, options?: RequestInit): Promise<Response> => {
  const urlStr = typeof url === 'string' ? url : (url as URL).toString();
  const isPlaceholder = urlStr.includes("placeholder-co-db.supabase.co");

  // Réponses de démonstration (données synthétiques, jamais certifiées) servies quand aucun backend n'est configuré.
  const getMockFunctionsResponse = (urlPath: string): any => {
    if (urlPath.includes('extract-leasing')) {
      return {
        contracts: [
          {
            lessee_name: "TRANSPORTS DEMO SARL",
            lessee_id: "MF887222",
            lessee_email: "contact@transports-demo.example.test",
            lessee_phone: "+216 30 000 000",
            contract_ref: "LSG-2024-8192",
            contract_status: "active",
            start_date: "2024-01-10",
            end_date: "2029-01-10",
            maturity_date: "2029-01-10",
            duration_months: 60,
            asset_type: "Matériel Industriel",
            asset_description: "Générateur Electrique Triphasé 500kVA",
            asset_value: 120000,
            residual_value: 12000,
            monthly_rent: 2400,
            total_amount: 144000,
            remaining_capital: 110000,
            interest_rate: 7.5,
            payment_frequency: "monthly",
            next_payment_date: "2026-06-10",
            overdue_amount: 4800,
            overdue_days: 35,
            risk_score: 45,
            risk_level: "medium",
            ai_confidence: 94,
            notes: "Retard de 1 échéance en cours de régularisation"
          }
        ]
      };
    }

    if (urlPath.includes('extract-dossier')) {
      return {
        dossiers: [
          {
            debtor_name: "DEBITEUR ALPHA DEMO",
            debtor_email: "alpha@sarl.tn",
            debtor_phone: "+216 30 000 000",
            amount: 145000,
            due_date: "2024-03-15"
          },
          {
            debtor_name: "PARTICULIER DEMO 01",
            debtor_email: "particulier.demo@example.test",
            debtor_phone: "+216 30 000 000",
            amount: 22000,
            due_date: "2024-03-14"
          }
        ]
      };
    }

    if (urlPath.includes('credit-decision')) {
      return {
        recommandation: {
          decision: "Acceptation conditionnelle",
          escalade_requise: false
        },
        resume: {
          recommandation_synthetique: "Dossier solide financièrement avec d'accords stables et un endettement acceptable, mais requiert une garantie de premier rang du dirigeant en raison du faible historique bureau de crédit sur le marché tunisien.",
          niveau_risque_global: "Modéré"
        },
        scoring_global: {
          score: 74,
          niveau_confiance: 92,
          calcul_detail: "Scoring = P1 (Situ. pro: 80% * 25%) + P2 (Financement: 72% * 25%) + P3 (Finances: 90% * 20%) + P4 (Garanties: 65% * 15%) + P5 (Histo: 50% * 15%)"
        },
        piliers: [
          {
            id: 1,
            ponderation: 25,
            nom: "Situation & Capacité d'Emprunt",
            score_qualitatif: "Fort",
            score_numerique: 80,
            analyse: "L'ancienneté professionnelle et la stabilité des revenus nets sont très confortables.",
            justification: "CDI de plus de 5 ans dans un secteur stable.",
            indicateurs_cles: { "Ancienneté": "5 ans", "Stabilité": "Excellente" }
          },
          {
            id: 2,
            ponderation: 25,
            nom: "Financement & Viabilité de l'Objet",
            score_qualitatif: "Acceptable",
            score_numerique: 72,
            analyse: "La durée demandée de l'amortissement est en adéquation avec la durée de vie de l'actif.",
            justification: "Taux d'intérêt sollicité aligné sur les conditions moyennes.",
            indicateurs_cles: { "Durée": "60 mois", "Produit": "Prêt demandé" }
          },
          {
            id: 3,
            ponderation: 20,
            nom: "Situation Financière & DSCR",
            score_qualitatif: "Fort",
            score_numerique: 90,
            analyse: "Les revenus nets couvrent amplement les charges fixes du ménage.",
            justification: "Le taux d'endettement net après octroi reste très vertueux (inférieur à 30%).",
            indicateurs_cles: { "Endettement": "28%", "Surplus mensuel": "Élevé" }
          },
          {
            id: 4,
            ponderation: 15,
            nom: "Garanties & Collatéral",
            score_qualitatif: "Acceptable",
            score_numerique: 65,
            analyse: "Le collatéral proposé présente une valeur d'hypothèque ou de cautionnement satisfaisante.",
            justification: "Besoin d'une validation juridique de 1er rang des sûretés.",
            indicateurs_cles: { "Garantie": "Hypothèque", "LTV": "75%" }
          },
          {
            id: 5,
            ponderation: 15,
            nom: "Historique & Antécédents de Crédit",
            score_qualitatif: "Fragile",
            score_numerique: 50,
            analyse: "Absence d'incident enregistré sur la centrale des risques au cours des 12 derniers mois.",
            justification: "Relations bancaires encore jeunes sur ce segment.",
            indicateurs_cles: { "Incidents 12m": "Zéro", "Relation": "Jeune" }
          }
        ],
        red_flags: [
          {
            niveau: "Faible",
            type: "Information",
            description: "Historique bureau de crédit jeune ou limité.",
            impact_score: "-5pts"
          }
        ],
        facteurs_favorables: [
          {
            type: "Revenus",
            description: "Revenus exceptionnels du demandeur assurant un service continu de la dette.",
            impact_score: "10"
          }
        ],
        conditions_suggerees: [
          {
            priorite: "Obligatoire",
            type: "Garantie",
            description: "Constitution d'une hypothèque de 1er rang sur l'actif financé."
          }
        ],
        donnees_analysees: {
          donnees_manquantes: [
            "Justificatif d'assurance multirisque habitation."
          ]
        },
        audit_trail: {
          logique_decisionnelle: "Réponse de démonstration — cadre indicatif Bâle III (moteur RecovAI, aide à la décision uniquement, aucune certification).",
          hypotheses_appliquees: [
            "Stabilité résiduelle de l'activité du débiteur.",
            "Valorisation conservatrice à hauteur de 80% du bien immobilier coté."
          ],
          conformite: "Cadre Bâle III indicatif — démonstration, non certifié",
          version_moteur: "1.4.1",
          timestamp_analyse: "2026-05-30"
        }
      };
    }

    if (urlPath.includes('ifrs9-engine')) {
      return {
        recommandation: {
          decision: "Acceptation conditionnelle",
          escalade_requise: false
        },
        resume: {
          recommandation_synthetique: "Evaluation prospective IFRS 9 qualifiant le dossier en Bucket 2 en raison d'un retard technique temporaire supérieur à 30 jours (ASRC), mais avec un recouvrement hautement probable grâce au bon profil financier général.",
          niveau_risque_global: "Modéré",
          bucket_anticipe: "Bucket 2",
          sppi_statut: "Sain (SPPI Passé)",
          evaluation_comptable: "Coût amorti compatible"
        },
        scoring_global: {
          score: 68,
          niveau_confiance: 95,
          calcul_detail: "Scoring ECL = PD (12 mois: 1.5% | Life: 4.8%) * LGD (32%) * EAD (échéances programmées). Amorti conforme.",
          pd_estimee: "4.8% (Durée de vie)",
          lgd_estimee: "32% (Collatéralisé)"
        },
        ifrs9: {
          test_sppi: {
            resultat: "Validé (SPPI)",
            consequence_comptable: "Éligible au classement au coût amorti selon IFRS 9. Clause d'intérêt standard sans indexation complexe ni effet de levier.",
            clauses_evaluees: [
              "Uniquement remboursement de principal et d'intérêts sur le principal.",
              "Pas d'indexation exotique externe ou de clause de conversion de créance."
            ]
          },
          classification_bucket: {
            bucket: "Bucket 2",
            horizon_ecl: "ECL Durée de vie (Lifetime)",
            justification: "Retard de paiement récent ou augmentation significative du risque de crédit (ASRC/SICR) basé sur les indicateurs d'historique.",
            impact_provisionnement: "Provision calculée sur la perte attendue à maturité du crédit (Lifetime)."
          },
          asrc: {
            sicr_detecte: true,
            justification: "Le dossier enregistre des signaux de transition du risque de crédit originel, notamment une modification de la note interne.",
            retard_jours: 35,
            indicateurs: [
              "Retards récurrents observés entre 15 et 40 jours.",
              "Déclassement sectoriel mineur."
            ]
          },
          forward_looking: {
            scenario_central: "Stabilité macro-économique du PIB tunisien (+1.8%) et du taux directeur de la BCT.",
            scenario_baissier: "Choc inflationniste et hausse du coût de l'énergie pesant sur la solvabilité.",
            impact_pd: "Hausse pondérée de +0.8% de la PD dans le cas d'un scénario de ralentissement."
          },
          modifications: {
            restructuration_detectee: false,
            test_decomptabilisation: "Sans restructuration majeure requérant décomptabilisation à cette étape."
          }
        },
        piliers: [
          {
            id: 1,
            ponderation: 25,
            nom: "Analyse SPPI contractuelle",
            score_qualitatif: "Fort",
            score_numerique: 95,
            analyse: "Flux de trésorerie uniquement représentatifs de remboursement de principal et d'intérêts.",
            justification: "Clauses standard de marché.",
            indicateurs_cles: { "Taux d'intérêt": "Classique / Indexé TMM", "Conversion": "Aucune" }
          },
          {
            id: 2,
            ponderation: 25,
            nom: "Augmentation significative du risque (SICR)",
            score_qualitatif: "Fragile",
            score_numerique: 45,
            analyse: "Détection d'une augmentation significative du risque de crédit depuis la comptabilisation initiale.",
            justification: "Retards temporaires cumulés.",
            indicateurs_cles: { "ASRC": "Oui", "Impact Bucket": "Transition B1 -> B2" }
          },
          {
            id: 3,
            ponderation: 20,
            nom: "Forward-Looking & Facteurs macro-économiques",
            score_qualitatif: "Acceptable",
            score_numerique: 70,
            analyse: "Perspectives alignées sur le scénario de référence de l'établissement.",
            justification: "Hypothèses sectorielles réalistes.",
            indicateurs_cles: { "Scénario PIB": "Central", "Macro Employment": "Sensibilité" }
          },
          {
            id: 4,
            ponderation: 15,
            nom: "Mensurations de pertes attendues (ECL)",
            score_qualitatif: "Acceptable",
            score_numerique: 74,
            analyse: "Le provisionnement actuel couvre l'estimation prévisionnelle de défaut.",
            justification: "Sûretés solides.",
            indicateurs_cles: { "PD": "4.8%", "LGD": "32%" }
          },
          {
            id: 5,
            ponderation: 15,
            nom: "Restructurations & Processus de défaut",
            score_qualitatif: "Fort",
            score_numerique: 85,
            analyse: "Aucun défaut avéré (Bucket 3 / Stage 3) n'est identifié à l'heure actuelle.",
            justification: "Aucune procédure collective ou contentieux actif.",
            indicateurs_cles: { "Retard": "35 jours", "Défaut": "Non" }
          }
        ],
        red_flags: [
          {
            niveau: "Modéré",
            type: "SICR",
            description: "Retard de paiement cumulé supérieur à 30 jours, entraînant le reclassement en Bucket 2 de manière réglementaire.",
            impact_score: "-15pts"
          }
        ],
        facteurs_favorables: [
          {
            type: "Collatéral",
            description: "Excellente couverture par des sûretés réelles réduisant la perte finale en cas de défaut (LGD à 32%).",
            impact_score: "15"
          }
        ],
        conditions_suggerees: [
          {
            priorite: "Recommandé",
            type: "IFRS 9",
            description: "Provisionnement complémentaire à hauteur de l'ECL à maturité (Lifetime) réglementaire.",
            "lien_ifrs9": "ECL calculé à maturité"
          }
        ],
        donnees_analysees: {
          variables_forward_looking: [
            "Croissance PIB Tunisie (+1.8% scénario de base)",
            "Taux de chômage national projeté à 16.2%"
          ],
          donnees_manquantes: [
            "Bilan certifié du dernier exercice clos (optionnel pour validation définitive du scoring pro)."
          ]
        },
        audit_trail: {
          logique_decisionnelle: "Calculatrice de dégradation prospective RecovAI conforme IFRS 9 directive BCT 2024.",
          hypotheses_appliquees: [
            "Amortissement linéaire des flux futurs estimables.",
            "Taux de recouvrement historique sectoriel de 68% sur le collatéral."
          ],
          conformite: "Référentiels IFRS 9 & BCT cités à titre indicatif — démonstration",
          version_moteur: "2.1.0",
          timestamp_analyse: "2026-05-30"
        }
      };
    }

    if (urlPath.includes('extract-contentieux')) {
      return {
        dossier: {
          assigned_attorney: "Maître Slim Ben Achour",
          court_name: "TPI Tunis (Maison Carrée)",
          procedure_type: "Commandement de payer suivi de saisie",
          claim_amount: 145000,
          last_major_act: "Établissement du commandement de payer par huissier"
        }
      };
    }

    return { success: true, result: "mock_response" };
  };

  // If it's the unconfigured placeholder URL, reply with mock structures immediately
  if (isPlaceholder) {
    let payload: any = [];
    if (urlStr.includes('/auth/v1/')) {
      if (urlStr.includes('/token') || urlStr.includes('/user')) {
        payload = {
          access_token: "dummy-token",
          token_type: "bearer",
          expires_in: 3600,
          refresh_token: "dummy-refresh-token",
          user: {
            id: "dummy-user-id",
            aud: "authenticated",
            role: "authenticated",
            email: "demo-agent@recovai.tn",
            email_confirmed_at: "2026-05-30T13:50:33Z",
            user_metadata: {
              full_name: "Agent de Recouvrement (Démo)"
            }
          }
        };
      } else {
        payload = {
          data: {
            session: {
              access_token: "dummy-token",
              token_type: "bearer",
              expires_in: 3600,
              refresh_token: "dummy-refresh-token",
              user: {
                id: "dummy-user-id",
                aud: "authenticated",
                role: "authenticated",
                email: "demo-agent@recovai.tn"
              }
            },
            user: {
              id: "dummy-user-id",
              aud: "authenticated",
              role: "authenticated",
              email: "demo-agent@recovai.tn"
            }
          }
        };
      }
    } else if (urlStr.includes('/storage/v1/')) {
      payload = { signedUrl: "https://placeholder-co-db.supabase.co/mock-url", path: "mock-path" };
    } else if (urlStr.includes('/functions/v1/')) {
      payload = getMockFunctionsResponse(urlStr);
    } else if (urlStr.includes('/rest/v1/')) {
      const restPath = urlStr.substring(urlStr.indexOf('/rest/v1/'));
      try {
        return await window.fetch(restPath, options);
      } catch (e) {
        console.warn('[Supabase client] Local REST fetch fallback:', e);
      }
    }
    return new Response(JSON.stringify(payload), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });
  }

  try {
    return await window.fetch(url, options);
  } catch (error) {
    console.warn(`[Supabase Safe Fetch Alert] Request to ${urlStr} failed:`, error);
    
    // In case of physical network failure (Failed to fetch), intercept paths and return correct mock structures
    let payload: any = [];
    if (urlStr.includes('/auth/v1/')) {
      payload = {
        access_token: "dummy-token",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "dummy-refresh-token",
        user: {
          id: "dummy-user-id",
          aud: "authenticated",
          role: "authenticated",
          email: "demo-agent@recovai.tn",
          email_confirmed_at: "2026-05-30T13:50:33Z",
          user_metadata: {
            full_name: "Agent de Recouvrement (Démo)"
          }
        }
      };
    } else if (urlStr.includes('/functions/v1/')) {
      payload = getMockFunctionsResponse(urlStr);
    } else if (urlStr.includes('/storage/v1/')) {
      payload = { signedUrl: "https://placeholder-co-db.supabase.co/mock-url", path: "mock-path" };
    }
    
    return new Response(JSON.stringify(payload), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: safeFetch
  }
});
